### ISSUE TITLE
Automatic assignment of ID and alphanumeric ID

### ISSUE THREAD

**Issue by acka47** [kaiec/reqbase#12]
Currently, one has to type in the IDs and alphanumeric IDs oneself. It makes more sense and would facilitate the inputprocedure if these IDs were assigned automatically by the system.

**Comment by boschthomas** [comment]
- when new content is created, some fields (e.g. ID, alphanumeric ID) should be filled automatically.
- ID according to the pattern: UC-<consecutive number> [for the content type Use Case]
- alphanumeric ID: content of the field 'label', trim spaces, upper-case

**Comment by scor** [comment]
Best would be to write a custom module to handle that. Alternatively, you could check https://www.drupal.org/project/computed_field
